name: personal_assistant
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  map_location_picker: ^1.2.8+3
  geolocator: ^10.1.0
  shared_preferences: ^2.0.12

  geocoding: ^2.1.1
  flutter_dnd: ^0.1.4+1
  google_maps_flutter: ^2.5.3
  cron: ^0.6.0
  awesome_notifications: ^0.8.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

